parameters:
#    lpe_yopnote.example.class: LPE\YopnoteBundle\Example

services:
#    lpe_yopnote.example:
#        class: %lpe_yopnote.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
