<?php

namespace LPE\YopnoteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavRepository extends EntityRepository
{

    public function findByHash($hash)
    {
        $result = $this->getEntityManager()
            ->createQuery('SELECT f FROM LPEYopnoteBundle:Fav f WHERE f.hash = :hash')
	    ->setParameter('hash',$hash)
            ->getResult();
	if(sizeof($result)==0)
	    return null;
	return $result[0];
    }
}
